package com.jaravir.tekila.module.system;

/**
 * Created by sajabrayilov on 06.02.2015.
 */
public enum SystemEvent {

    PAYMENT_VOIDED("PAYMENT_VOIDED"),
    PAYMENT("PAYMENT"),
    PAYMENT_PROCCESSED("PAYMENT_PROCCESSED"),
    PROVISIONING("PROVISION"),
    REPROVISION("REPROVISION"),
    NOTIFICATION("NOTIF"),
    SUBSCRIPTION_CREATED("SBN_CREATED"),
    SUBSCRIPTION_STATUS_BLOCK("SBN_STATUS_BLOCK"),
    SUBSCRIPTION_STATUS_ACTIVE("SBN_STATUS_ACTIVE"),
    SUBSCRIPTION_STATUS_SUSPEND("SBN_STATUS_SUSPEND"),
    SUBSCRIPTION_STATUS_CANCEL("SBN_STATUS_CANCEL"),
    SUBSCRIPTION_STATUS_FINAL("SBN_STATUS_FINAL"),
    SUBSCRIPTION_STATUS_PARTIALLY_BLOCKED("SUBSCRIPTION_STATUS_PARTIALLY_BLOCKED"),
    SUBSCRIPTION_PROLONGED("SBN_PROLONGED"),
    SUBSCRIPTION_PROLONGED_FOR_ONE_TIME("SBN_PROLONGED_ONE_TIME"),
    SUBSCRIPTION_REACTIVATION("SBN_REACTIVE"),
    SUBSCRIPTION_REACTIVATION_ADDED("SBN_REACTIVE_SCHEDULED"),
    SUBSCRIPTION_SETTING_MODIFIED("SBN_SET_MODIFIED"),
    SUBSCRIPTION_BILLED("SBN_BILLED"),
    SUBSCRIPTION_DISCONNECT_SESSION("SBN_SESSION_DISCON"),
    SUBSCRIPTION_CHANGE_SERVICE("SBN_CHANGE_SERVICE"),
    SUBSCRIPTION_TOPUP_PROMO_BALANCE("SBN_TOPUP_PROMO"),
    SUBSCRIPTION_CAMPAIGN_PROCESSED("SBN_PROMO_PROC"),
    SUBSCRIPTION_CAMPAIGN_JOINED("SBN_PROMO_JOIN"),
    SUBSCRIPTION_CAMPAIGN_BONUS_USED("SBN_PROMO_BONUS_USED"),
    SUBSCRIPTION_CAMPAIGN_ACTIVE("SBN_PROMO_ACTIVE"),
    SUBSCRIPTION_AFTER_BILLED("SBN_AFTER_BILLED"),
    INVOICE_STATE_CHANGED("INV_STATE"),
    INVOICE_CREATED("INV_CREATED"),
    INVOICE_CLOSED("INV_CLOSED"),
    INVOICE_VOIDED("INV_VOIDED"),
    EQUIPMENT_RESERVED("EQUIP_RSRV"),
    EQUIPMENT_UNRESERVED("EQUIP_UNRSRV"),
    EQUIPMENT_TRANSFERED("EQUIP_TRANSFER"),
    MINIPOP_RESERVED("MINIPOP_RSRV"),
    MINIPOP_UNRESERVED("MINIPOP_UNRSRV"),
    CHARGE("CHARGE"),
    VAS_ADDED("VAS_ADDED"),
    VAS_STATUS_BLOCK("VAS_STATUS_BLOCK"),
    VAS_STATUS_ACTIVE("VAS_STATUS_ACTIVE"),
    VAS_STATUS_FINAL("VAS_STATUS_FINAL"),
    NOTIFICATION_ADDED("NOTIF_ADDED"),
    NOTIFICATION_SCHEDULED("NOTIF_SCHEDULED"),
    NOTIFICATION_SENT("NOTIF_SENT"),
    SERVICE_INITIALIZED("SERVICE_INIT"),
    BILLING_START("BILLING_START"),
    BILLING_END("BILLING_END"),
    LIFECYLCE_START("LIFECYCLE_START"),
    LIFECYCLE_END("LIFECYCLE_END"),
    LOGIN_FAILED("LOGIN_FAILED"),
    LOGIN_SUCCESS("LOGIN_SUCCESS"),
    LOGOUT("LOGOUT"),
    PASSWORD_CHANGED("PASSWORD_CHANGED"),
    PERMISSION_DENIED("PERM_DENIED"),
    IP_ADDRESS_RESERVED("IP_RSRV"),
    IP_ADDRESS_UNRESERVED("IP_UNRSRV"),
    SERVICE_ADD_STATUS_CHANGE_RULE("SRV_ADD_STATUS_CHANGE_RULE"),
    SERVICE_REMOVE_STATUS_CHANGE_RULE("SRV_REMOVE_STATUS_CHANGE_RULE"),
    JOB_EXECUTION("JOB_EXEC"),
    JOB_ADDED("JOB_ADD"),
    SUBSCRIPTION_ACTIVATION_REPROCESS("SBN_STATUS_ACTIVE_REPROCESS"),
    SALES_PARTNER_CREATED("SALES_PARTNER_CREATED"),
    SALES_PARTNER_STORE_CREATED("SALES_PARTNER_STORE_CREATED"),
    SALES_PARTNER_INVOICE_CREATED("SALES_PARTNER_INV_CREATED"),
    SALES_PARTNER_CHARGED("SALES_PARNER_CHARGE"),
    SALES_PARTNER_STORE_EQUIPMENT_ADDED("SALES_PARTNER_STORE_EQUIP_ADDED"),
    SALES_PARTNER_STORE_EQUIPMENT_REMOVED("SALES_PARTNER_STORE_EQUIP_REMOVED"),
    USER_CREATED("USER_CREATED"),
    BALANCE_TRANSFER("BALANCE_TRANSFER"),
    COMPENSATION_ADD("COMPENSATION_ADD"),
    LATE_FEE("LATE_FEE"),
    SOAP("SOAP"),
    SUBSCRIPTION_DELETED("SUBSCRIPTION_DELETED"),
    SUBSCRIPTION_CAMPAIGN_DELETED("SUBSCRIPTION_CAMPAIGN_DELETED"),
    SUBSCRIPTION_REINITIALIZED("SUBSCRIPTION_FINAL_TO_INITIAL"),
    SUBSCRIPTION_PROMO_BALANCE_DEBIT("SUBSCRIPTION_PROMO_BALANCE_DEBIT"),
    SKIP_BILLING_FINAL("FINAL_STATUS_SUBSCRIPTION_SKIPPED"),
    CONVERGENT("CONVERGENT"),
    SUSPEND_ON_BILLING("SUSPEND_ON_BILLING"),
    PARTIAL_PROMO_TRANSFER("PARTIAL_PROMO_TRANSFER"),
    RESET_PROMO_BALANCE("RESET_PROMO_BALANCE"),
    COUNTER_SUSPEND_ON_BILLING("COUNTER_SUSPEND_ON_BILLING"),
    CHARGE_CANCELLED("CHARGE_CANCELLED"),
    SUBSCRIPTION_STATUS_PRE_FINAL("SBN_STATUS_PRE_FINAL"),
    IPTV_PROVISIONED("IPTV_PROVISIONED"),
    SIP_NUMBER_ADDED("SIP_NUMBER_ADDED"),
    SIP_NUMBER_MODIFIED("SIP_NUMBER_MODIFIED"),
    SIP_NUMBER_REMOVED("SIP_NUMBER_REMOVED"),
    CONTRACT_UPDATES("CONTRACT_UPDATES"),
    USER_BLOCKED("USER_BLOCKED"),
    USER_UNBLOCKED("USER_UNBLOCKED"),
    SUBSCRIPTION_CAMPAIGN_SUSPENDED("SBN_CAMPAIGN_SUSPENDED"),
    ACTIVATE_SUSPENDED_CAMPAIGN("ACTIVATE_SUSPENDED_CAMPAIGN");


    private final String code;

    SystemEvent(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public static SystemEvent convertFromCode(String code) {
        if (code != null && !code.isEmpty()) {
            for (SystemEvent event : values())
                if (event.getCode().equals(code))
                    return event;
        }


        return null;
    }
}